    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install lynis dependencies
      become: true
      apt:
        name: gpg
        state: present

    - name: prepare lynis installation
      become: true
      shell: |
        curl -fsSL https://packages.cisofy.com/keys/cisofy-software-public.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/cisofy-software-public.gpg
        echo "deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/cisofy-software-public.gpg] https://packages.cisofy.com/community/lynis/deb/ stable main" | sudo tee /etc/apt/sources.list.d/cisofy-lynis.list

    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install lynis
      become: true
      apt:
        name: lynis
        state: present

    - name: update and run first lynis audit
      become: true
      shell: |
        lynis update info
        lynis audit system | ansi2html -l > /tmp/lynis-report.html 
        echo "First Lynis report see attachment" | mail -A /tmp/lynis-report.html -s "Lynis report" {{ mail_to }}