    - name: Main-Playbook
      hosts: debian-server
      remote_user: "{{ user_name }}"
      gather_facts: yes
      vars_files: ./group_vars/variables.yml

      roles:
        - packages
        - ssh
        - password-quality
        - unattended-upgrades
        - firewall
        - mail
        - clamav
        - rkhunter
        - auditd
        - lynis