    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install packages
      become: true
      apt:
        name: 
          - apt-listchanges
          - apt-transport-https
          - apticron
          - audispd-plugins
          - auditd
          - ca-certificates
          - clamav
          - clamav-daemon
          - clamav-freshclam
          - curl
          - fail2ban
          - host
          - libpam-pwquality
          - mailutils
          - msmtp
          - msmtp-mta
          - psad
          - rkhunter
          - ufw
          - unattended-upgrades
        state: present
