
    - name: secure ssh configuration 
      become: true
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          ########################################################################################################
          # start settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2019-01-01
          ########################################################################################################
          # Supported HostKey algorithms by order of preference.
          HostKey /etc/ssh/ssh_host_ed25519_key
          HostKey /etc/ssh/ssh_host_rsa_key
          HostKey /etc/ssh/ssh_host_ecdsa_key
          KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
          Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
          MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
          # LogLevel VERBOSE logs user's key fingerprint on login. Needed to have a clear audit track of which key was using to log in.
          LogLevel VERBOSE
          # Use kernel sandbox mechanisms where possible in unprivileged processes
          # Systrace on OpenBSD, Seccomp on Linux, seatbelt on MacOSX/Darwin, rlimit elsewhere.
          # Note: This setting is deprecated in OpenSSH 7.5 (https://www.openssh.com/txt/release-7.5)
          # UsePrivilegeSeparation sandbox
          ########################################################################################################
          # end settings from https://infosec.mozilla.org/guidelines/openssh#modern-openssh-67 as of 2019-01-01
          ########################################################################################################
          # don't let users set environment variables
          PermitUserEnvironment no
          # only use the newer, more secure protocol
          Protocol 2
          # disable port forwarding
          AllowTcpForwarding no
          AllowStreamLocalForwarding no
          GatewayPorts no
          PermitTunnel no
          # don't allow login if the account has an empty password
          PermitEmptyPasswords no
          # ignore .rhosts and .shosts
          IgnoreRhosts yes
          # verify hostname matches IP
          UseDNS yes
          Compression no
          TCPKeepAlive no
          AllowAgentForwarding no
          # don't allow .rhosts or /etc/hosts.equiv
          HostbasedAuthentication no
      notify: restart ssh service

    - name: secure ssh configuration part 2
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^AllowGroups', line: 'AllowGroups sshusers' }
        - { regexp: '^ClientAliveCountMax', line: 'ClientAliveCountMax 0'}
        - { regexp: '^ClientAliveInterval', line: 'ClientAliveInterval 300'}
        - { regexp: '^ListenAddress', line: 'ListenAddress 0.0.0.0'}
        - { regexp: '^LoginGraceTime', line: 'LoginGraceTime 30'}
        - { regexp: '^MaxAuthTries', line: 'MaxAuthTries 2'}
        - { regexp: '^MaxSessions', line: 'MaxSessions 2'}
        - { regexp: '^MaxStartups', line: 'MaxStartups 2'}
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no'}
        - { regexp: '^Port', line: 'Port {{ ssh_port }}'}
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no'}
        - { regexp: '^X11Forwarding', line: 'X11Forwarding no'}
        - { regexp: '^Subsystem', line: 'Subsystem sftp  internal-sftp -f AUTHPRIV -l INFO'}
      notify: restart ssh service

    - name: remove short diffie diffie-hellman
      become: true
      shell: |
        awk '$5 >= 3071' /etc/ssh/moduli | sudo tee /etc/ssh/moduli.tmp
        mv /etc/ssh/moduli.tmp /etc/ssh/moduli
      notify: restart ssh service